<?php

namespace minsal\academicaAnBundle\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionRepository extends EntityRepository
{
    public function seleccionarPorcentajeMayores()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT e 
                           FROM minsalacademicaAnBundle:Evaluacion e
                           WHERE e.porcentaje > 0.5
                           ORDER BY e.id ASC')
                ->getResult();
    }
}
